### ISSUE TITLE
Can't we close this repo?

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim-0#1]
Since we have got things working elsewhere, can I just remove the repo? @mokun @shirishag75

**Comment by shirishag75** [comment]
where elsewhere ? Are you talking about https://github.com/mars-sim/mars-sim-git . If that's the go-to-place now, then yes you can certainly remove the repo.

**Comment by mokun** [comment]
I'm actually using this /mars-sim-0 repo for experimentation :)

I wanna avoid messing with the /mars-sim repo, where all the important Wikis and Issues are resided.

To break this down, I'm still trying to figure out how to 
1. Backup all the Issues in /mars-sim repo and restore them in /mars-sim-git
2. Backup all the Wikis in /mars-sim repo and restore them in /mars-sim-git

OR:

3. Clone the code in  /mars-sim-git repo and restore them in /mars-sim with Commit History intact

So, it's either doing 3 or doing 1 & 2.

**Comment by mokun** [comment]
I can do step 3 above now.

I've tested it successfully by cloning the code in /mars-sim-git repo and pushing them in /mars-sim-0 repo here, as you can see. 

All the commit history are intact. Plus it also carries over whatever release tags from /mars-sim-git

If I do that, those [11 release tags](https://github.com/mars-sim/mars-sim/releases) currently in /mars-sim repo be gone and won't be preserved.

@larsnaesbye , is it easy to rebuild all the release tags ?

**Comment by mokun** [comment]
I'm created a new repo call /releases just for preserving those zip and tar.gz. see https://github.com/mars-sim/releases/releases
